### ISSUE TITLE
Performance comparison with other smaller versions of Transformers

### ISSUE THREAD

**Issue by manueltonneau** [cgraywang/transformer-on-diet#1]
Hi all and thanks for this cool contribution :) 

As I read your paper, I haven't been able to find a comparison of the "Transformer on diet" performance with other smaller models (ALBERT, DistilBERT, BERT-of-Theseus, etc..) on classic downstream task benchmarks (SQUaD, etc..). Are you planning to publish results for this?

**Comment by cgraywang** [comment]
Hi @mananeau , thanks for your interests! The short answer: we haven't done the comparison between the light architectures with our approach. Note that (probably you already know) the main difference between our architecture and other light architectures (e.g., ALBERT) is that, our architecture is just one layer of alternative Transformer. We can then stack the alternative (light) Transformer layer to generate another BERT. We aim to present some experimental insight between different human derived light Transformers (parameters vs performance). Please feel free to grep the basic architecture to do some experiments, or contribute to this repo. If you have any questions, please feel free to let me know. Thanks.

**Comment by manueltonneau** [comment]
Sounds good. Looking forward to the experimental insights! Thanks for your reply :)
